lisphilar/covid19-sir

covsirphy/analysis/simulator.py, covsirphy/ode/mbase.py, covsirphy/ode/sewirf.py, covsirphy/ode/sir.py, covsirphy/ode/sird.py, covsirphy/ode/sirf.py, covsirphy/ode/sirfv.py, setup.cfg
I think this was caused by non-dimensional ODE.
However, to keep development speed, I will close this issue with a minor change of codes.
It is necessary to revise the codes of classes to simulate ODE models and to perform dimensionalized numerical simulations.
Advantage of non-dimensional system:
- we can estimate the parameter values efficiently and compare the parameter values
- we can compare the parameter values with that of the other countries easily
Dis-advantage of non-dimensional system (may be root cause of issue#1):
- substraction in diferencial equations reduces the accuracy of numerical simulation
- it is difficult to determine the minimum value of dydt
- dimensionalization of simulated values increases error with actual values
=> fix: issue#1 - Long-term ODE simulation shows negative number of cases

.gitignore
Added `kaggle.json` to .gitignore to avoid uploading Kaggle API keys to the repository.
This is related to #26 and #27
=> add: kaggle.json to .gitignore

covsirphy/__init__.py, covsirphy/analysis/scenario.py, covsirphy/cleaning/population.py, covsirphy/util/error.py
(Refactoring)
Add `deprecate` decorator in error.py
This enables us to show deprecation warning with easy way.
```Python
from covsirphy.util.error import deprecate
...
@deprecate(old="old method name", new="new method name")
def ...
```
=> update: decorator for deprecation

covsirphy/cleaning/country_data.py, covsirphy/cleaning/jhu_data.py, covsirphy/cleaning/oxcgrt.py, covsirphy/cleaning/population.py, covsirphy/cleaning/word.py
This is related to #42 and #49.
KeyError will be raised when the expected columns are not included in the raw data.
=> add: KeyError when not include expected cols

covsirphy/analysis/scenario.py, covsirphy/phase/phase_series.py, tests/test_scenario.py
This is related to #118 
We can add past phases as follows.
```Python
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu(local_file="./input/covid_19_data.csv")
population_data = data_loader.population(local_file="./input/locations_population.csv")
scenario = cs.Scenario(jhu_data, population_data, country="US")
scenario.remove()
scenario.add_phase(end_date="01May2020")
scenario.add_phase(end_date="01Jun2020")
scenario.add_phase()
scenario.summary()
```
or,
```Python
scenario.remove()
scenario.add_phase(days=30)
scenario.add_phase(days=30)
scenario.add_phase()
scenario.summary()
```
When both of `end_date` and `days` are None, the end date will be the last date of the records.
=> fix: removement of 0th phase in Scenario class

covsirphy/cleaning/country_data.py
This is related to #120 
- Remove empty rows from country level data
- Fill NAs with 0 in country level data
=> fix: remove empty rows from country level data

covsirphy/analysis/scenario.py
This is related to #202, #203 and #206
=> fix: ignore error whhen drop

covsirphy/cleaning/dataloader.py
This is related to #210 and #212 
Rather than raw records, records cleaned by COVID-19 Data Hub will be used.
=> update: use dataset cleaned by data resource

covsirphy/analysis/scenario.py, covsirphy/phase/phase_series.py, example/usage_phases.ipynb, tests/test_phase_series.py, tests/test_scenario.py
This is related to #228 
"include_initial_phase" of `Scenario.trend() will be True as default.
=> update: include initial phase as default

README.md, docs/markdown/INSTALLATION.md
This is related to #261 
It will be recomended to use the datasets of COVID-19 Data Hub in Kaggle platfom.
=> docs: use COVID-19 Data Hub in Kaggle

input.py
This is related to issues #266, #267.
Updated `input.py` script with the correct population pyramid path for extracting the relative datasets under `kaggle/input/population-pyramid-2019/` folder.
=> fix: population-pyramid path in input.py script

covsirphy/phase/sr_change.py, tests/test_phase_series.py, tests/test_phase_unit.py, tests/test_policy_measures.py, tests/test_scenario.py
This is related to #270 
- Removed interpolation and sampling in S-R trend analysis.
- Updated test codes to shorten runtime of tests.
=> remove: imterpolation and sampling of S-R

covsirphy/simulation/estimator.py
This is related to #291 
Default value of `Estimator.run(timeout)` was changed from 60 to 180.
With `Estimator` class, CovsirPhy continues estimation while runtime does not over `timeout` and max simulated number of cases is not in the range of `(max actual number * 0.98, max actual number * 1.02)`.
=> update: default value of estimation timeout to 180

README.md, docs/markdown/INSTALLATION.md, setup.cfg
This is related to #335 
Support Python 3.6.
Tests will be performed Python 36 and 3.8 with semaphore CI.
=> support Python 3.6

covsirphy/analysis/scenario.py, tests/test_scenario.py
This is related to #319 
Add `past_days` argument to`Scenario.score()` method so that we can specify the phases in score calculation with how many past days.
=> Issue319 past days

covsirphy/cleaning/jhu_data.py
This is related to #334 .
FIx NA values in the output of `JHUData._complement_recovered_full()`. NA values will be changed to 0.
=> fix: Na values in full complement

covsirphy/analysis/scenario.py, example/scenario_analysis.py, tests/test_scenario.py
This is related to #367 
`Scenario.records_diff(variables=None, windows=7, show_figure=True, filename=None)` was created.
`variables` can be selected from Confirmed, Infected, Fatal and Recovered.
If None was set to `variables`, ["Confirmed", "Fatal", "Recovered"] will be used.
=> add: Scenario.records_diff()

covsirphy/phase/phase_estimator.py, covsirphy/phase/sr_change.py, covsirphy/worldwide/policy.py, tests/test_policy_measures.py
This is related to #373 .
`MPEstimater._run()` uses `JHUData.records()` rather than `JHUData.subset()`.
=> fix: ValueError in PolicyMeasures.estimate()

covsirphy/__init__.py, covsirphy/analysis/param_tracker.py, covsirphy/analysis/scenario.py, covsirphy/cleaning/country_data.py, covsirphy/cleaning/term.py, covsirphy/phase/phase_unit.py, covsirphy/util/error.py, covsirphy/worldwide/policy.py, tests/test_phase_unit.py
This is related to #359.
`UnExecutedError` was created to explain that we have unexecuted methods that we need to run in advance. This is a child class of `AttributeError`, `NameError` and `ValueError`.
=> Issue359 unexecuted

covsirphy/cleaning/jhu_data.py, tests/test_dataloader.py
This is related to #339 
When the number of recovered cases is too large when outbreaking, full complement on recovered data will be done.
=> add: full complement when R >> I when outbreaking

covsirphy/cleaning/dataloader.py, covsirphy/cleaning/jhu_data.py, covsirphy/cleaning/linelist.py, tests/test_dataloader.py
This is related to #357.
-  `LinelistData.recovery_period()` calculates median value of recovery period.
- `DataLoader.jhu()` will download linelist data as well as the dataset of COVID-19 Data Hub are returns `JHUData` instance, calling `DataLoader.linelist()` internally.
- `DataLoader.jhu()` will set `.recovery_period` property with the value of recovery period [days] calculated with `LinelistData.recovery_period()`.
- `JHUData._complement_recovered_full()` uses the expected value of recovery period set with `.recovery_period` property.
=> Issue357 recovery period

covsirphy/cleaning/cbase.py, covsirphy/cleaning/dataloader.py, covsirphy/cleaning/japan_data.py, covsirphy/cleaning/jhu_data.py, covsirphy/cleaning/linelist.py, example/dataset_load.py
This is related to #383 .
`DataLoader.jhu()` will call `DataLoader.japan()` internally to replace Japan dataset of COVID-19 Data Hub with that of https://github.com/lisphilar/covid19-sir/tree/master/data
=> add: DataLoader.jhu() calls .japan() internally

covsirphy/analysis/data_handler.py, covsirphy/cleaning/jhu_data.py
This is related to #382.
Figure titles of `Scenario.records()` with complement will be selected from
- "Cases over time" (when not complemented),
- "Cases over time with monotonic increasing complemented confirmed data",
- "Cases over time with monotonic increasing complemented fatal data",
- "Cases over time with monotonic increasing complemented recovered data",
- "Cases over time with fully complemented recovered data", or
- "Cases over time with partially complemented recovered data".
E.g.
=> update: title of .records() when complement

covsirphy/analysis/example_data.py, tests/test_dataloader.py
This is follow-up for #382.
`ExampleData` class, a child class of `JHUData`, does not need complement methods. Becuase of this, `ExampleData.subset_complement()` and `ExampleData.records()` will return the same outputs with `ExampleData.subset()`.
=> follow-up: no complement on example data

covsirphy/cleaning/jhu_complement.py
This is follow-up for #382.
In the figure title of `Scenario.records`, new line will be added when many complement methods is applied.
=> update: new line when may complement

covsirphy/simulation/estimator.py
This is related to #402.
Suppress `UserWarning` in `Estiamtor.history()`.
=> supress: UserWarning in plotting

covsirphy/analysis/data_handler.py, tests/test_scenario.py
Follow-up for #422
Accept `variables=["Susceptible"]` in `Scenario.records()`.
=> fu: accept Susceptible in Scenario.records()

covsirphy/cleaning/cbase.py, covsirphy/cleaning/dataloader.py, covsirphy/cleaning/pcr_data.py, docs/markdown/INSTALLATION.md, example/dataset_load.py, tests/test_datahub.py
#429 
Use PCR dataset (ISO3 code, date, the number of tests) retrieved from "Our World In Data" to update `PCRData`. `PCRData" created by `DataLoader` class will have two data source, COVID-19 Data Hub and this new dataset.
=> add: update PCRData with "Our World In Data"

covsirphy/cleaning/dataloader.py, covsirphy/cleaning/pcr_data.py, tests/test_datahub.py
#429
Only when `PCRIncorrectPreconditionError` is raised in `PCRData._pcr_check_preconditions()`, retrieve the data from "Our World In Data" for the country and retry `PCRData._pcr_check_preconditions()` with this new dataset.
=> Issue429 pcr not default

covsirphy/cleaning/jhu_complement.py
#450 
Updated `JHUDataComplementHandler._recovered_partial()` to update the filling solution of partial complement of recovered data. The number of daily new cases will be filled with forward method and coumulative values of daily values will be used as the complemented recovered data.
(Before: directly filled recovered values with forward solution of `.interpolate()`.)
=> update: filling diff values in partial complement

covsirphy/cleaning/jhu_complement.py, covsirphy/cleaning/jhu_data.py, tests/test_datahub.py
This is related to #401, #450
For issue #401, new method `show_complement()` in `JHUData` class was created for returning the kind of complement that was done for JHU subset for all the available countries or for specified country/countries.
For issue #450, improved `_recovered_partial()` and `_recovered_partial_ending()`. For overcoming the constant ending diff values upon complementing, these ending diff values were interpolated in order to create some kind of variance.
=> fix: partial and ending partial complement + show complement new method

covsirphy/cleaning/jhu_complement.py
This is relevant to issue #488.
Added stricter condition using max_ignored for confirmed in _recovered_partial()
=> fix: stricter condition in _recovered_partial()

covsirphy/cleaning/jhu_data.py
#483 
Close #483 
i.e. Sync the last date of `JHUData.total()` with the last records of COVID-19 Data Hub data.
=> fix: unexpected JHUData.total() final date

.github/workflows/full_test.yml, docs/markdown/INSTALLATION.md, poetry.lock, pyproject.toml
#480 
Support Python 3.6.9 (for Google Colab) by downgrading scipy (1.6.0 -> 1.5.4) and japanmap (0.023 -> 0.021).
=> Issue480 python369

covsirphy/cleaning/jhu_complement.py, covsirphy/cleaning/jhu_data.py
Related to #514.
Follow-up reworks for `df.copy` usage. Also added checks for partial recovery periods in `_calculate_recovery_period_country()`.
=> fix: reworks in recovery periods validation

covsirphy/analysis/param_tracker.py, covsirphy/analysis/scenario.py, tests/test_scenario.py
#511
Add `phases=None` (default) argument to select phases to show in `Scenario.history()`/`Scenario.simulate()` method.
=> add: "phases" argument

docs/markdown/INSTALLATION.md, poetry.lock, pyproject.toml
#480 and #516
- For #480, downgrade `matplotlib` from 3.3.3 to 3.2.1 (Restart of runtime in Google colab will not be necessary)
- For #516, downgrade `numpy` from 2.9.5 to 2.9.1 (to fix `AttributeError` in installation with Kaggle Notebook)
- Update installation guide to install CovsirPhy in Kaggle/Google Colab
=> Issue516 dep

docs/markdown/INSTALLATION.md
#516 
To note that
`!pip uninstall typing -y` is necessary only when using **development versions** of CovsirPhy with Kaggle Notebook.
=> docs: necessity of uninstall of typing

covsirphy/cleaning/country_data.py, tests/test_dataloader.py
#555 and #557
- Add `CountryData.register_total()` to register total value of all provinces as country level data.
- Close #557: `ValueError: invalid literal for int() with base 10: '0.0'` when `running `country_data.cleaned()`.
=> add: register total as country level data

covsirphy/simulation/estimator.py, tests/test_scenario.py
#578 
Add pruner argument to Scenario.estimate() (internally, `Estimator.run()`).
Users will select pruners and keyword aruments of pruners as follows.
- `Scenario.estimate(cs.SIRF, pruner="hyperband")`
- `Scenario.estimate(cs.SIRF, pruner="median")`
- `Scenario.estimate(cs.SIRF, pruner="threshold", upper=0.5)`
- `Scenario.estimate(cs.SIRF, pruner="percentile", percentile=50)`
=> Issue578 selectable pruners

covsirphy/cleaning/jhu_data.py
#596 
to revert https://github.com/lisphilar/covid19-sir/commit/c55faabfa9b113fe0c81798a095463dc156050f4, replaced
```Python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
try:
return int(pd.Series(valid_periods).median())
except DeprecationWarning:
pass
```
with
```Python
if valid_periods:
return int(pd.Series(valid_periods).median())
```
`warnings.filterwarnings("ignore", category=DeprecationWarning)` changed the warning with Anaconda to a fatal error.
=> update: stop supressing DeprecationWarning

covsirphy/analysis/data_handler.py, covsirphy/analysis/scenario.py
#626 and #622
- Fix: Scenario.records_diff() creates two figures
- Fix: varname.utils.VarnameRetrievingError when running tests with `pytest` and GitHub Actions
=> fix: Scenario.records_diff() creates two figures

covsirphy/analysis/data_handler.py, poetry.lock, pyproject.toml
#622
Follow-up for #622, remove `nameof` to fix `varname.utils.VarnameRetrievingError`.
=> fix: VarnameRetrievingError by removing nameof

covsirphy/analysis/param_tracker.py, covsirphy/analysis/scenario.py, covsirphy/trend/sr_change.py, covsirphy/trend/trend_detector.py, tests/test_trend.py
#670
We can select algorithms of change detection.
```Python
snl = cs.Scenario(country="Italy")
snl.register(jhu_data, population_data)
snl.trend(algo="Binseg-normal")
```
Argument `algo` will be selected from "Pelt-rbf", "Binseg-rbf", "Binseg-normal", "BottomUp-rbf" and "BottomUp-normal". At this time, the default value is "Pelt-rbf" and this means we use the same algoritm as that in the previous version.
=> Issue670 select algo in trend

covsirphy/cleaning/jhu_complement.py, covsirphy/cleaning/pcr_data.py
This is related to issue #681.
Changed interpolation method from `spline` to `linear` inside `jhu_complement` and `pcr_data`.
=> fix: changed interpolation method from spline to linear

covsirphy/analysis/param_tracker.py, covsirphy/analysis/scenario.py, covsirphy/phase/phase_series.py, covsirphy/trend/trend_detector.py, tests/test_phase_series.py
#670 and #686
- `TrendDetector(..., min_size=7)` as default
- `TrendDetector(algo="Binseg-normal")` as default
- When `min_size=None` with `Scenario.trend()`, `min_size` for S-R trend anlysis will be set as the delay period calculated with `Scenario.estimate_delay()`
- Close #686: use mode value of delay period
=> Issue670 default

covsirphy/analysis/scenario.py
Follow-up of #691
Fix that the variables specified with `Scenario.simulate(variables)` does not change the variables in the output figure.
=> fix: variable names un-selectable with .simulate()

covsirphy/__init__.py, covsirphy/analysis/scenario.py, covsirphy/regression/param_elastic_net.py, covsirphy/regression/reg_handler.py, covsirphy/regression/regbase.py, covsirphy/util/evaluator.py, tests/test_util.py
#668 
For refactoring, I created `covsirphy.regression.reg_handler.RegressionHander` class. This is called in `Scenario.fit()` and `Scenario.predict()`.
`RegressionHandler.fit()` executes some regressors (only `_ParamElasticNetRegressor` for "Indicators -> Parameters  with Elastic Net" at this time) and select the best model for forecasting beased on the scores with test dataset.
When we need to add some regressors, we will create a child class of `covsirphy.regbase._RegressionBase` with class variable `.DESC` (regressor description), method `._fit()` and `.predict()`. Then, update `RegressionHandler.fit()`.
=> Issue668 predictor

covsirphy/regression/rate_elastic_net.py, covsirphy/regression/reg_handler.py, example/scenario_analysis.py, tests/test_scenario.py
#668
Add "Indicators(n)/Indicators(n-1) -> Parameters(n)/Parameters(n-1) with Elastic Net" approach to forecasting.
Now we have the following two apporoaches and the best approaches will be selected with test scores. Approaches which lead un-expected parameter values (i.e. not in range (0, 1)) will not be selected.
- "Indicators -> Parameters with Elastic Net"
- Indicators(n)/Indicators(n-1) -> Parameters(n)/Parameters(n-1) with Elastic Net
=> Issue668 rate

covsirphy/ode/ode_handler.py, covsirphy/ode/ode_solver.py, covsirphy/ode/ode_solver_multi.py, covsirphy/ode/param_estimator.py, tests/test_ode.py
#718
Bug fix for parameter estimation with actual records and update stdout in `ODEHandler`. `start_date` was renamed to `first_date` for multi-phased simulation . Additionally, we can apply `pandas.Timestamp` instance as `first_date`.
=> Issue718 type

covsirphy/analysis/scenario.py, covsirphy/regression/reg_handler.py, covsirphy/util/evaluator.py, tests/test_scenario.py, tests/test_util.py
#731
When `delay=(7, 31)` (not default currently), `Scenario.fit()` select the best delay value with grid search to minimize the score of `RegressionHandler.fit()`.
=> Issue731 grid

covsirphy/ode/mbase.py, covsirphy/ode/ode_handler.py, covsirphy/ode/param_estimator.py, covsirphy/ode/sewirf.py, covsirphy/ode/sir.py, covsirphy/ode/sird.py, covsirphy/ode/sirf.py, tests/test_ode.py
#718
For SIR, SIR-D, SIR-F model,
- `model.guess(data, tau, q=0.5)` returns 0.5 quantiles of parameter values
- `model.guess(data, tau, q=(0.1, 0.9))` returns 0.1 and 0.9 quantiles of parameter values
`model.param_range()` will not be used in parameter estimation and replaced with `model.guess(..., q=(0.1, 0.9))`.
Note that `cs.SIRF.guess(q=<float>)["theta"]` is always 0.0 and  `cs.SIRF.guess(q=<tuple(<float>, <float>)>)["theta"]` is always (0.0, 0.5), not (0.0, 1.0).
=> Issue718 guess

covsirphy/ode/ode_handler.py, covsirphy/ode/ode_solver_multi.py, covsirphy/ode/param_estimator.py
#718
Update the output of `ODEHandler.estimate()` to include reproduction number and day parameters (1/beta [days] and so on).
=> update: include Rt, tau and day_param in info

covsirphy/cleaning/pcr_data.py, covsirphy/visualization/colored_map.py, tests/test_cleaning/test_pcr.py
This is related to issues #745 and #747.
1. Added argument `last_date` in `PCRData.positive_rate()`.
2. Use horizontal legend in colored maps
Call example for `PCRData.positive_rate()`:
```
data_loader = cs.DataLoader()
pcr_data = data_loader.pcr()
country = "Italy"
pcr_data.positive_rate(country, last_date="21Apr2021")
```
=> Add option for last date limit to PCRData.positive_rate() + simplify colored maps legend

covsirphy/__init__.py, covsirphy/analysis/example_data.py, covsirphy/analysis/param_tracker.py, covsirphy/analysis/scenario.py, covsirphy/ode/mbase.py, covsirphy/ode/ode_handler.py, covsirphy/ode/sewirf.py, covsirphy/ode/sir.py, covsirphy/ode/sird.py, covsirphy/ode/sirf.py, covsirphy/phase/phase_estimator.py, covsirphy/phase/phase_series.py, covsirphy/phase/phase_unit.py, covsirphy/simulation/estimator.py, covsirphy/simulation/simulator.py, covsirphy/worldwide/policy.py, tests/test_deprecated/test_param_tracker.py, tests/test_deprecated/test_phase_series.py, tests/test_deprecated/test_phase_unit.py, tests/test_deprecated/test_policy_measures.py, tests/test_example_data.py, tests/test_ode.py
#718
- `ExampleData` will use `ODEHandler`, not old `ODESimulator`
The following classes will be deprecated.
- `model.param_range()`, `model.specialize()` and `model.restore()` for `SIR`, `SIRD and `SIRF`
- `worldwide.PolicyMeasures`
- `simulation.Estimator`
- `simulation.Simulator`
- `phase.MPEstimator`
- `phase.PhaseSeries`
- `phase.PhaseUnit`
- `analysis.ParamTracker`
=> Issue718 example data

covsirphy/analysis/phase_tracker.py, covsirphy/analysis/scenario.py, covsirphy/util/term.py, example/usage_quick.ipynb, tests/test_phase_tracker.py, tests/test_scenario.py
#718 and #725
With pull request, we can focus on the values in specified date range with the following arguments. Internally, these arguments are parsed by `PhaseTracker.parse_range()`.
- `dates`: tuple of start date and end date
- `past_days` (integer): how many past days to use in calculation from today (`Scenario.today` property)
- `phases` (list of str): phase names to use in calculation
These arguments are effective with `Scenario.history()`, `Scenario.simulate()`, `Scenario.track()` and `Scenario.score()`.
Regarding #718 and #725, Documentation will be also updated with usage_quick.ipynb.
https://lisphilar.github.io/covid19-sir/usage_quick.html
=> Issue725 dates

covsirphy/analysis/example_data.py, covsirphy/analysis/phase_tracker.py, covsirphy/analysis/scenario.py, covsirphy/ode/sewirf.py, tests/test_deprecated/test_param_tracker.py, tests/test_deprecated/test_phase_series.py, tests/test_deprecated/test_phase_unit.py, tests/test_deprecated/test_policy_measures.py, tests/test_example_data.py
#718
Fix some bugs related to #718.
- `Scenario.add()` did not work when we used `ExampleData` as `JHUData`
- Unexpected dtype (expected: `np.int64`, un-expected: `object`) was returend by `ExampleData.subset()`
- The order of variables defined by `SEWIRF.VARIBLES` was not S/E/W/I/R/F. S/I/R/F/E/W was returned.
=> Issue718 scenario with example data

covsirphy/analysis/phase_tracker.py, covsirphy/analysis/scenario.py
#718
Bug fix related to #718 updating.
- When we future phases, population values were float values, not integers, in summary.
- In retrospective study, parameter estimation was done for all phases. This should be done in the phases which start after the beginning date.
=> Issue718 retrospective

covsirphy/__version__.py, covsirphy/regression/param_decision_tree.py
#813
- Use `regressor__max_depth": list(range(1, 10))` as the grid of max depth of decision tree regressor
- Use min-max scaler just before PCA and decision tree regrression
=> update: use min-max scaler just before PCA

covsirphy/__version__.py, covsirphy/regression/regbase.py
#813
In `RegressorBase._split()`, backword filling (`pandas.DataFrame.bfill()`) was done with delayed indicator values to keep the number of train/test data. 
```Python
X_delayed = X.copy()
for delay in delay_values:
X_delayed = X_delayed.join(X.shift(delay, freq="D"), how="outer", rsuffix=f"_{delay}")
X_delayed = X_delayed.ffill().bfill()
```
However, this lead over fitting because un-existed combination of parameter values and indicators were created. This should be like this.
```Python
X_delayed = X.copy()
for delay in delay_values:
X_delayed = X_delayed.join(X.shift(delay, freq="D"), how="outer", rsuffix=f"_{delay}")
X_delayed = X_delayed.ffill() # .bfill()
```
=> update: remove bfill() in X

covsirphy/__version__.py, covsirphy/ode/param_estimator.py
#833
- Use `Scenario.estimate(<model>, timeout_iteration=1)` as default.
- Use `constant_liar=False` explicitly.
=> Issue833 use `timeout_iteration=1` as default with `Scenario.estimate`

covsirphy/loading/loaderbase.py, example/scenario_analysis.py, example/usage_quick.ipynb, tests/test_loading.py
#851 and #853
Close #853.
`.collect()` method was added to `_LoaderBase` class, which is the parent class of `DataLoader`. `_LoaderBase` will be also used as the parent class of `LocalDataLoader` class, which will be implemented for #851.
=> new: _LoaderBase.collect()

covsirphy/cleaning/country_data.py, docs/markdown/INSTALLATION.md
#856
- Add `CountryData.cleaned(date_format)` argument to specify appropreate date format.
- When `None` (default), `pandas.to_datetime()` will parse date strings automatically.
- When `"%d/%m/%Y"`, date strings will be parsed with this format.
- Update documentation: https://lisphilar.github.io/covid19-sir/markdown/INSTALLATION.html#use-a-local-csv-file-which-has-the-number-of-cases
=> [New] Specify strftime format with CountryData.cleaned(date_format)

covsirphy/regression/feature_engineer.py, covsirphy/regression/reg_handler.py
#842 and #860
- Close #860 
- #842: Because "delay" is necessary to create X_target, delay period should be applied to all indicators, including features created by the other tools.
=> add: log-transformed

covsirphy/loading/covid19datahub.py, covsirphy/loading/dataloader.py, covsirphy/loading/db_base.py, tests/test_loading.py
#851
Perform database lock for both of local datasets and remote dataset from COVID-19 Data Hub.
Locking "Our World In Data" records will be implemented later.
Verbosity and basenames of CSV files for remote datasets will be determined by users with `DataLoader(basename_dict=None, verbose=1)`. `DataLoader.jhu(basename, verbose=1)` and so on will be deprecated.
=> Issue851 lock including COVID-19 Data Hub data

covsirphy/cleaning/cbase.py, covsirphy/cleaning/population.py, covsirphy/cleaning/vaccine_data.py, covsirphy/loading/dataloader.py, covsirphy/loading/db_base.py, covsirphy/loading/db_covid19dh.py, covsirphy/loading/db_owid.py
#851
Lock "Our World In Data" vaccine dataset before calling `DataLoader.vaccine()` as well as "COVID-19 Data Hub" data. This was required to use local datasets at country level with `VaccineData`.
Not included in this pull request:
- `VaccineData` parses province level data
- Lock PCR data before calling `DataLoader.pcr()`
=> Issue851 lock OWID coutry level vaccine data

covsirphy/cleaning/vaccine_data.py, covsirphy/loading/dataloader.py
#851
- New: parse province-level vaccination data
- Fix: duplicated citations with `DataLoader`, use set(citations)
- Refactoring
=> Issue851 parse province-level vaccination data

covsirphy/__version__.py, covsirphy/cleaning/pcr_data.py, covsirphy/loading/dataloader.py, covsirphy/loading/db_base.py, covsirphy/loading/db_covid19dh.py, covsirphy/loading/db_owid.py, tests/test_cleaning/test_pcr.py
#851
Include PCR data to locked database  by `DataLoader.lock()`.
Records of the number of vaccinations and tests will be saved in ourworldindata.csv as default.
(Before ourworldindata_vaccine.csv and ourworldindata_pcr.csv)
=> Issue851 lock PCR data from OWID

covsirphy/loading/dataloader.py
#851
- Resample data before database lock to ensure all dates has values.
- Clarify the all arguments of `DataLoader.lock()` by stoping using `kwargs`.
=> Issue851 resample

covsirphy/loading/dataloader.py
#851
Use local dataset with the following script.
```Python
loader = cs.DataLoader(update_interval=None)
loader.read_csv("input/cook county.csv", parse_dates=["date"], dayfirst=False)
loader.local
loader.assign(country="US", population=5150233)
loader.local
loader.lock(date="date", country="country", province="province", confirmed="confirmed", fatal="fatal", population="population")
loader.locked
jhu_data = loader.jhu()
snl = cs.Scenario(country="US", province="Cook")
snl.register(jhu_data)
snl.interactive = False
snl.records(filename="input/cook.png")
```
=> fix: KeyError when lock local data

covsirphy/__version__.py, covsirphy/cleaning/japan_data.py, covsirphy/loading/dataloader.py, covsirphy/loading/db_cs_japan.py, covsirphy/loading/db_owid.py, covsirphy/util/term.py
#851
Include Japan dataset in database lock.
Because of this, `JHUData.replace()` will not be called in `DataLoader.jhu()` and the other methods. Downloading will be done with `_CSJapan` internally.
Fix inccorect country name setting with the loader for "Our World In Data".
=> update: include Japan data inlocked database

covsirphy/analysis/phase_tracker.py
#895 
Internal variable `PhaseTracker._track_df` is a dataframe with time index (Date) and many columns, including estimated parameter values and estimated **DAY** parameter values (1/beta [day] etc.). Simulation needs parameter values saved in this dataframe.
At the previous version 2.21.0-lambda-fu1, all rows which have any NA cells are ignored by `.dropna()`. When **DAY** parameters are NAs, this implementation lead to empty data for simulation unexpectedly and raised the error `covsirphy.util.error.UnExecutedError: Please execute ODEHandler.add() in advance.`
With this pull request, only rows which have NAs as parameter values  will be ignored. NAs of parameter values are not acceptable in simulation, but NAs of **DAY** parameter values are acceptable in simulation because *DAY** …
=> fix: dropped necessary rows when simulating

covsirphy/loading/db_google.py, covsirphy/visualization/colored_map.py
#862 and #909
- Close #862 
- Fix: Some province names are registered with unicodes in mobility data and this raises name discrepancies with the other recommended datasets.
- Close #909
=> fix: some province names include unicodes

covsirphy/science/ode_scenario.py
#1045
- fix: `IntCastingNaNError` with `ODEScenario.compare_cases()`
- update; return date objects as argmax in `ODEScenario().describe()`
- update: not display figures of simulation, `ODEScenario().represent()`
=> fix:  IntCastingNaNError and string returned as dates

poetry.lock, pyproject.toml
#1161
- Use deptry version 0.23 to suppress the warning regarding `mpl_toolkit`.
=> config: #1161. use deptry 0.2.3 to remove warning

tests/test_cleaning/test_japan_data.py
#1173
`japan.csv" and "covid_japan_metadata.csv" created with `JapanData` class and test workflow will be moved to "input" directory from top directory.
=> test: #1173, move created files with test_japan_data.py to input dir

covsirphy/downloading/provider.py
#1160
- Specify "utf-8" as the encoding when downloading CSV files.
=> update: #1160, specify encoding

.github/workflows/test.yml, poetry.lock, pyproject.toml
- #1203
- Use `pytest-xdust` in tests
=> test: use pytest-xdist

.github/workflows/test.yml
#1159
- test: refactor test workflow because datatable installation is un-necessary with Python 3.10
=> test: refactor test workflow because datatable installation is un-necessary with Python 3.10

.github/workflows/test.yml
#1259 and #1263
- Close #1259 by using Python 3.10 instead of Python 3.9 for tests with Poetry
Close #1263 by updating quality check workflow to run it for all updates of default branch and pull requests.
=> Run quality check workflow for all updates of default branch and pull requests

covsirphy/downloading/downloader.py, docs/conf.py, poetry.lock, pyproject.toml
#1258
- use type hints in APIs users will call: downloading
- show type hints in documentation using `sphinx_autodoc_typehints` and `sphinx.ext.intersphinx`
=> use type hints in APIs users will call: downloading

Makefile, covsirphy/downloading/downloader.py, covsirphy/dynamics/dynamics.py, covsirphy/dynamics/ode.py, covsirphy/dynamics/sewirf.py, covsirphy/dynamics/sir.py, covsirphy/dynamics/sird.py, covsirphy/dynamics/sirf.py, covsirphy/engineering/_complement.py, covsirphy/util/alias.py, covsirphy/util/validator.py, covsirphy/visualization/bar_plot.py, covsirphy/visualization/compare_plot.py, covsirphy/visualization/line_plot.py, covsirphy/visualization/scatter_plot.py, covsirphy/visualization/vbase.py, docs/conf.py, poetry.lock, pyproject.toml
#1258
- use type hints in APIs users will call: dynamics
- use `pyright` as type checker
- fix/suppress errors of type hints found by `pyright`
- update intersphinx mapping to link with numpy and matplotlib in docs/conf.py
=> Use type hint in APIs of dynamics and add `pyright` check to quality check workflow

poetry.lock, pyproject.toml, tests/test_visualization/test_scatter.py
#1233
Close #1233 by reverting test skip and use `pandas` version 1.5.1.
=> revert test skip and use pandas 1.5.1

Makefile, covsirphy/dynamics/ode.py, covsirphy/science/_autots.py, covsirphy/science/ml.py, covsirphy/util/evaluator.py, poetry.lock, pyproject.toml, tests/test_util/test_evaluator.py
#1265, #1290, #1291
- Close #1265 by using `numpy` instead of `sklearn.metrics` in `Evaluator` class, and import `autots` and `pca` inside methods because they have `sklearn` as a dependency, making importing time slow.
- Close #1290 by adding `make importtime` command as a development tool.
- Close #1291 by removing `metrics` argument of `Evaluator().score()` because `metrics` exist.
=> Improve importing time and add make command for evaluation

poetry.lock, pyproject.toml
#1295
Close #1295 by ignore pytest.PytestDeprecationWarning in tests.
=> ignore pytest.PytestDeprecationWarning in tests

covsirphy/visualization/scatter_plot.py, tests/test_visualization/test_scatter.py
#1309
Close #1309 by delegating error handling of colormap to Matplotlib.
=> Delegate error handling of colormap to Matplotlib

covsirphy/gis/_layer.py
#1350
Close #1350 by supress the following warning, referencing https://github.com/geopandas/geopandas/pull/2645 and https://github.com/pandas-dev/pandas/issues/48673
```Python
FAILED tests/test_engineering/test_engineer.py::test_with_actual_data - DeprecationWarning:
In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace
instead of always setting a new array.
To retain the old behavior, use either `df[df.columns[i]] = newvals` or,
if columns are non-unique, `df.isetitem(i, newvals)`
```
=> close #1350

README.md
=> Removed warning on README for using covsirphy with Google Colab

covsirphy/downloading/_provider.py, pyproject.toml
#1413 
We use Pandas version >= 2.0.0 and date_format argument.
=> Use pandas 2.0.0 and date_format argument of pandas.read_csv()

.github/workflows/deploy.yml, .github/workflows/test.yml
#1417
Close #1417 by updating version of cancel-workflow-action from 0.10.0 to 0.11.0 to fix warning in workflow.
=> update version of cancel-workflow-action from 0.10.0 to 0.11.0 to fix warning in workflow

covsirphy/downloading/_db_covid19dh.py, covsirphy/dynamics/dynamics.py, covsirphy/engineering/_cleaner.py, covsirphy/engineering/_complement.py, covsirphy/engineering/_transformer.py, covsirphy/gis/_layer.py, covsirphy/gis/gis.py
#1511, #1513, #1514, #1515
- Close #1511 by ignoring FutureWarning.
- Close #1513 by adding `.iloc`
- Close #1514 by adding `observed=True` to `.groupby()`
- Close #1515 by casting province column from `float64` to `object` and suppressing the warning (to be fixed by pandas version 3.0.0 release)
=> Fix errors regarding pandas version 2.1.0 release

.github/workflows/test.yml, poetry.lock, pyproject.toml
Follow-up #1593
Use Pytho 3.12 with flake8 v7.0.0 and pyproject-flake8 v7.0.0 in test workflow.
=> test: use Pyton 3.12 for test workflow

.github/workflows/deploy.yml, .github/workflows/pr_verify_linked_issue.yml, .github/workflows/rebase-pull-requests.yml, .github/workflows/test.yml
Close #1751
Use the latest versions of GitHub Actions for workflows.
=> use the latest versions of GitHub Actions for workflows
