lisphilar/covid19-sir

- covsirphy/analysis/scenario.py
- example/scenario_analysis.py
- setup.cfg
To calculate step number in a phase, tau value was fixed to 1440 [min].
> fix: issue#2 - Last date of ODE simulation does not match end date of the lastphase

- covsirphy/cleaning/country_data.py
For fix issue #8, `cleaned` method was re-activated in `cs.cleaning.country_data.CountryData.cleaned()`
> fix: issue #8

- .github/ISSUE_TEMPLATE/bug-issue-template.md
> Update issue templates

- covsirphy/phase/estimator.py
> fix: issue #11

- README.md
- covsirphy/__init__.py
- covsirphy/__version__.py
- setup.cfg
With this change,  we can get the version number using `covsirphy.__version__`
> Add covsirphy.__version__

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/word.py
- covsirphy/phase/estimator.py
- covsirphy/phase/phase_data.py
- covsirphy/phase/sr_data.py
- covsirphy/util/plotting.py
Refactoring for remove duplication and code complexity. Docstring was also updated.
> Refactoring

- covsirphy/cleaning/population.py
- tests/test_data_loader.py
> fix: statement of error

- covsirphy/cleaning/dataloader.py
This closes #51 
This is related to #42 and #51
> update: skip dataframe.to_csv when OSError

- covsirphy/analysis/scenario.py
- covsirphy/phase/estimator.py
This will close #62 and #15 
This will be included in v2.4.0
> Issue62 and issue15

- Pipfile
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/population.py
- setup.cfg
- tests/test_data_loader.py
> update: switch to COVID-19 Data Hub

- covsirphy/cleaning/dataloader.py
> fix: saving CSV files by data loader

- covsirphy/phase/estimator.py
> update: default value of timeout_iteration

- covsirphy/analysis/scenario.py
> fix: TypeError of scenario.param_history()

- covsirphy/analysis/sr_change.py
> fix: bug of column name replacement

- covsirphy/cleaning/population.py
- tests/test_data_loader.py
> fix: population.update

- covsirphy/analysis/example_data.py
- covsirphy/analysis/scenario.py
- covsirphy/analysis/sr_change.py
- covsirphy/cleaning/population.py
- covsirphy/phase/estimator.py
- covsirphy/phase/trend.py
> fix: order of import

- covsirphy/cleaning/jhu_data.py
> fix: location of KeyError

- covsirphy/cleaning/jhu_data.py
- input.py
Reverts lisphilar/covid19-sir#111
> Revert "Issue110"

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/jhu_data.py
> Issue110 trial2

- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/term.py
- covsirphy/phase/sr_change.py
- covsirphy/phase/trend.py
- tests/test_change_finder.py
This is related to #110 and #116
> Issue110 trial3

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/term.py
- covsirphy/phase/sr_change.py
- covsirphy/phase/trend.py
> update: not show lines when too large RMSLE

- covsirphy/cleaning/population.py
> update: remove NAs from population data

- covsirphy/cleaning/population.py
> fix: drop population records mistakenly

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/cbase.py
- covsirphy/phase/phase_series.py
- example/usage_phases.ipynb
- example/usage_quick.ipynb
- tests/test_scenario.py
This is related to #140 
- fix: recover 0th phase when combine and separate 
- fix: supress errors of dependencies
> Issue140 2nd

- covsirphy/__init__.py
> fx: surpress SyntaxWarnings

- .semaphore/semaphore.yml
Create workflow to use semaphore 2.0 for test and docs
> Use Fan-in / Fan-out starter workflow

- Makefile
- Pipfile
> update: dependencies, aiohttp

- covsirphy/__init__.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/term.py
- covsirphy/phase/phase_unit.py
- covsirphy/simulation/estimator.py
- covsirphy/simulation/simulator.py
- covsirphy/util/argument.py
This is related to #167 
- Add 'PhaseUnit' class to perform paramer estimation of one phase
This is not linked to 'Scenario' at this time.
> add: PhaseUnit class

- covsirphy/analysis/example_data.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/term.py
- covsirphy/ode/mbase.py
- covsirphy/phase/phase_series.py
- covsirphy/phase/phase_unit.py
- covsirphy/phase/sr_change.py
- covsirphy/phase/trend.py
- covsirphy/simulation/estimator.py
- covsirphy/simulation/optimize.py
- covsirphy/simulation/simulator.py
- covsirphy/worldwide/policy.py
- example/long_simulation.py
- example/scenario_analysis.py
- example/worldwide.py
- tests/test_change_finder.py
- tests/test_ode.py
- tests/test_scenario.py
This is related to #167 
Revised the PolicyMeasures/Scenario/PhaseSeries class with PhaseUnit
> Issue167 trial4

- Makefile
- Pipfile
- covsirphy/__init__.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/term.py
- covsirphy/phase/phase_estimater.py
- covsirphy/phase/phase_estimator.py
- covsirphy/phase/phase_series.py
- covsirphy/phase/phase_unit.py
- covsirphy/phase/sr_change.py
- covsirphy/simulation/estimator.py
- covsirphy/simulation/optimize.py
- covsirphy/util/stopwatch.py
- covsirphy/worldwide/policy.py
- example/usage_quick.ipynb
- setup.cfg
- tests/test_ode.py
- tests/test_phase_series.py
- tests/test_phase_unit.py
- tests/test_scenario.py
> Issue167 trial5

- covsirphy/ode/mbase.py
- covsirphy/ode/sewirf.py
- covsirphy/ode/sir.py
- covsirphy/ode/sird.py
- covsirphy/ode/sirf.py
- covsirphy/ode/sirfv.py
- tests/test_scenario.py
> fix: ZeroDivisionError of estimation

- covsirphy/analysis/example_data.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/simulation/estimator.py
- example/dataset_load.py
- example/long_simulation.py
- example/scenario_analysis.py
- example/sewirf_model.py
- example/sir_model.py
- example/sird_model.py
- example/sirf_model.py
- example/sirfv_model.py
- example/trend_analysis.py
- example/worldwide.py
This is related to #196 
SettingWithCopyWarning raised by pandas
> Issue196 fu

- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/jhu_data.py
- tests/test_change_finder.py
> fix: AttributeError when data downloading

- covsirphy/cleaning/dataloader.py
> update: keep up with update of dependencies

- covsirphy/cleaning/term.py
> fix: condition of th

- covsirphy/analysis/scenario.py
This is related to #220
Docstring of `Scenario.delete()` was updated.
> update: docs, Scenario.delete()

- Pipfile
- Pipfile.lock
- setup.cfg
- tests/test_scenario.py
> dependency: add tabulate

- covsirphy/phase/phase_series.py
- tests/test_phase_series.py
> fix: length of new phase when .add(days)

- covsirphy/analysis/scenario.py
> fix: ValueError when delete last phase

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/term.py
> update: use "Reproduction number", not "Rt"

- covsirphy/analysis/scenario.py
This closes #252 
This colses #253
> fix: error code of Scenario.add()

- covsirphy/worldwide/policy.py
> fix: PolicyMeasures.param_history()

- covsirphy/worldwide/policy.py
> fix: ValueError in PolicyMeasures.trend()

- Pipfile.lock
- covsirphy/cleaning/dataloader.py
> fix: FileNotFoundError with dask.read_csv()

- input.py
> config: download Kaggle datasets used in notebook

- covsirphy/phase/trend.py
> fix: max number of iteration, trend analysis

- covsirphy/analysis/scenario.py
> update: title of simulation

- input.py
This is related to #267 
Save Kaggle datasets in the sub-directories of "kaggle/input" directory.
> update: use sub-directories for kaggle datasets

- example/scenario_analysis_deu.py
- example/scenario_analysis_grc.py
- example/scenario_analysis_jpn.py
- example/scenario_analysis_usa.py
This is related to #272
Length of the future phase was changed from [days from today to 31Mar2021] to 7 days.
> example: update the length of future phase

- example/scenario_analysis_deu.py
- example/scenario_analysis_grc.py
- example/scenario_analysis_jpn.py
- example/scenario_analysis_usa.py
This is related to #272 
Arguments of Scenario.add()
> example: fix argument of Scenario.add()

- covsirphy/analysis/scenario.py
- covsirphy/simulation/estimator.py
> fix: OverflowError in Scenario.retrospective()

- Makefile
- docs/index.rst
- docs/markdown/TERM.md
> docs: term definition

- covsirphy/phase/sr_change.py
- covsirphy/phase/trend.py
- tests/test_change_finder.py
- tests/test_phase_series.py
This is related to #282 and revised tests.
Dear @Inglezos ,
Please review my changes of tests regarding #282 (using linear function in S-R trend analysis).
> test: update for using linear function in trend

- covsirphy/cleaning/covid19datahub.py
- covsirphy/cleaning/dataloader.py
- tests/test_dataloader.py
This is related to #281 and follow-up of #301 
- Memory issues
> Issue281 covid19datahub

- covsirphy/phase/sr_change.py
- covsirphy/phase/trend.py
This is related to issue #307.
> fix: wrong trends RMSLE conditions for selecting best dataframe

- covsirphy/phase/trend.py
This is related to pull request #308.
> fix: reworked solution for trends analysis bug in Trend.run()

- covsirphy/__init__.py
- covsirphy/simulation/estimator.py
- covsirphy/util/optimize.py
> move: Optimizer from simulation to util

- covsirphy/phase/phase_estimator.py
- covsirphy/simulation/estimator.py
- covsirphy/util/stopwatch.py
This is related to #291 
- Refactoring
> Refactoring for issue291

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/term.py
- covsirphy/ode/sirf.py
- covsirphy/simulation/estimator.py
- example/sewirf_model.py
- example/sir_model.py
- example/sird_model.py
- example/sirf_model.py
- example/sirfv_model.py
- tests/test_ode.py
- tests/test_policy_measures.py
- tests/test_scenario.py
This is related to #291
- RMSLE score calculated with `np.sqrt(sklearn.metrics.mean_squared_log_error(x1, x2))` will be directory used in `Estimater.error_f`.
- SIR-F model: weights of variables in parameter estimation error function will be changed from (`S, I, R, F) = (1, 1, 1, 1)` to (0, 1, 1, 1)`
- Test of `PolicyMeasures`: only uses two countries
> Issue291 rmsle

- covsirphy/cleaning/covid19datahub.py
- covsirphy/cleaning/dataloader.py
> add: verbosity of data loading

- covsirphy/cleaning/covid19datahub.py
This is related to #322 and update stdout.
> update: stdout of DataLoader.jhu()

- covsirphy/cleaning/covid19datahub.py
This is related to #322 and keep compatibility with standard output of `DataLoader.jhu(verbose=True)`.
> fix: compatibility

- covsirphy/analysis/model_validator.py
- covsirphy/worldwide/policy.py
- tests/test_ode.py
- tests/test_policy_measures.py
- tests/test_scenario.py
This is related to #291
Default value of `timeout` argument will be changed from 60 sec to 180 sec, according to revision of `Scenario.estimate(timeout)`.
> Issue291 model validator

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/term.py
- tests/test_scenario.py
This is related to #319 
`phases` argument will be added to `Scenario.score()` method so that users can select target phases for score calculation within this method.
> Issue319 phases

- Pipfile
- covsirphy/__init__.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/linelist.py
- example/load_linelist.py
- tests/test_dataloader.py
This is related to #281
`DataLoader.linelist()` method was added to download and cleaning linelist data of case reports.
> Issue281 linelist

- docs/markdown/INSTALLATION.md
This is related to #281 
Add documentation of linelist.
> docs: citation of linelist

- covsirphy/cleaning/jhu_data.py
This is related to #339 
Update filling method of `JHUData._cleaning()`.
> fix: JHUData._cleaning(), how to filling

- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/country_data.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/population.py
- covsirphy/cleaning/term.py
- example/usage_policy.ipynb
- tests/test_dataloader.py
- tests/test_ode.py
- tests/test_policy_measures.py
- tests/test_scenario.py
This is related to #340.
- Refactoring
- Add tests
> Issue339 refactor

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/simulation/estimator.py
- covsirphy/worldwide/policy.py
- tests/test_dataloader.py
This is related to #334 and #340 .
- Ensure Recovered shows monotonic increasing.
- WIth spline, interpolate recovered values full complemented.
- Update requirement of full complement to complement UK records.
> Issue340 use full

- covsirphy/__init__.py
- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/term.py
- covsirphy/phase/phase_series.py
- example/usage_phases.ipynb
- tests/conftest.py
- tests/test_param_tracker.py
- tests/test_phase_series.py
- tests/test_scenario.py
This is related to #354 .
Some methods of `Scenario` class were moved to `ParamTracker` class for refactoring. Usage and function werenot changed.
> Issue354 separate class

- covsirphy/cleaning/linelist.py
- example/load_linelist.py
- tests/conftest.py
- tests/test_dataloader.py
This is related to #360
`LinelistData.subset(country, province=None)` was updated to return all records in th country when province is not specified.
> fix: LinelistData.subset()

- tests/conftest.py
- tests/test_dataloader.py
This is related to #362 
remove linelist from conftest.py
> test: remove linelist from conftest.py

- tests/conftest.py
- tests/test_dataloader.py
- tests/test_param_tracker.py
- tests/test_scenario.py
This is related to #366 
Improve speed of tests with `pytest.fixture(scope="session")`.
> Test fixture

- covsirphy/analysis/scenario.py
- covsirphy/cleaning/jhu_data.py
- tests/test_dataloader.py
To refactor `Scenario` class, `JHUData.records()` was created. This method performs subsetting and complement, if necessary.
> refactor: create JHUData.records()

- covsirphy/__init__.py
- covsirphy/analysis/data_handler.py
- covsirphy/analysis/scenario.py
- tests/test_scenario.py
This is related to #367.
For maintenance, `DataHandler` class was created as the parent of `Scenario` class. Some methods for data loading and complement was moved to this new class. No impact on usage of `Scenario` class.
> Issue367 datahandler

- covsirphy/__init__.py
- covsirphy/analysis/example_data.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/linelist.py
- covsirphy/cleaning/population.py
- covsirphy/util/error.py
This is related to #359 
`SubsetNotFoundError` was created as a child class of `KeyError` and `ValueError`. This will be rased when the subset of dataset with user-specified arguments idoes not exist.
> add: SubsetNotFoundError

- covsirphy/__init__.py
- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/util/error.py
This is related to #359 .
`ScenarioNotFoundError`, child class of `KeyError`, will be raised when the scenario name is not registered.
Refoctoring was performed with `Scenario` and `ParamTracker` class.
> add: ScenarioNotFoundError

- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/jhu_data.py
- tests/test_param_tracker.py
- tests/test_policy_measures.py
- tests/test_scenario.py
This is related to #359.
- Follow-up for #376.
- Add tests of `ParamTracker` and `Scenario` class.
> Issue359 fu tracker

- covsirphy/__init__.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/country_data.py
- covsirphy/cleaning/covid19datahub.py
- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/japan_data.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/linelist.py
- covsirphy/cleaning/population.py
- tests/conftest.py
- tests/test_dataloader.py
This is related to #383.
Add Japan dataset at prefecture level to `DataLoader.japan()`.
> Issue383 prefecture

- covsirphy/__init__.py
- covsirphy/cleaning/jhu_complement.py
- covsirphy/cleaning/jhu_data.py
This is related to #382.
`JHUDataComplementHandler` will be created to refactor `JHUData` class. This class will perform complement of JHU dataset.
> add: JHUDataComplementHandler class

- covsirphy/analysis/example_data.py
This is follow-up for #382.
Update the outputs of `ExampleData.subset_complement()` and `ExampleData.records()`.
> update: the output of ExampleData.records()

- covsirphy/analysis/data_handler.py
This is follow-up for #382.
Figure title of `Scenario.records_diff()` will be updated to show the datails complement.
> update: title of Scenario.record_diff()

- covsirphy/__init__.py
- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/japan_data.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/term.py
- covsirphy/util/error.py
- example/dataset_load.py
- example/usage_dataset.ipynb
- tests/conftest.py
- tests/test_datahub.py
- tests/test_dataloader.py
This is follow-up for #389  and #383.
- Refactoring was done in `PCRData`, `JHUData`, `DataLoader` class.
- `PCRIncorrectPreconditions` was renamed to `PCRIncorrectPreconditionError`.
- "Tested" column was renamed to "Tests" column because this is the number of tests, not tested cases.
- "C_diff" was replaced with "Confirmed_diff".
- "PCR_Rate" was replaced with "Test_positive_rate"
- Class method `PCRData.from_dataframe()` was added.
- Removed legend in `PCRData.positive_rate()` figure.
- Example codes, documentation and tests codes were updated.
> Issue389 fu

- covsirphy/cleaning/country_data.py
- covsirphy/cleaning/jhu_data.py
- tests/test_datahub.py
- tests/test_dataloader.py
This is related to #403, #404, #406 
- Close #404 
- Close #406 
- Add tests for using local CSV file as JHU-style dataset
- Refactored
> Issue 404 406

- .github/CONTRIBUTING.md
- Makefile
- README.md
- docs/index.rst
- docs/markdown/INSTALLATION.md
- example/usage_dataset.ipynb
This is related to #403.
Documentation was updated to explain how to use local CSV files as JHU dataset.
> Issue403 docs

- covsirphy/__init__.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/covid19datahub.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/population.py
- tests/test_datahub.py
This is related to #389.
- Refactoring.
- Add tests of `PCRData`
> Issue389 fu test

- example/usage_theoretical.ipynb
This is related to #393.
Model descriptions of SIR/SIR-D/SIR-F/SEWIR-F model model were updated.
> docs: model description

- docs/markdown/TERM.md
> Added description of tau definition in TERM.md

- covsirphy/ode/sirfv.py
This is related to #417.
- Close #417
> fix: DeprectionWarning with SIRFV

- example/usage_theoretical.ipynb
This is related to #393 and #394.
As discussed in #394, description of alpha1 parameter was revised.
(Direct fatality probability of S* (non-dimentional) )
> docs: description of alpha1

- covsirphy/cleaning/jhu_complement.py
- covsirphy/cleaning/jhu_data.py
This is related to #427.
Improved _recovered_full() and added _recovered_partial_ending().
> improved full complement method + added _recovered_partial_ending()

- covsirphy/analysis/data_handler.py
- covsirphy/util/plotting.py
- tests/test_scenario.py
#438 and #422 (retry of #422)
- Close #438 
- Users can select variables to show using `Scenario.records(variables=["Confirmed", "Recovered"])`
- Users can select color map with `Scenario.records(colormap="tab10")`
- Users can select colors with `Scenario.records(color_dict={"Infected": "blue", "Fatal": "red", "Recovered": "green"})`
- Uses can select colors in `Scenario.records_diff()` in the same way
Color map will be selected from https://matplotlib.org/examples/color/colormaps_reference.html
Figure with `Scenario.records(variables=["Confirmed", "Recovered"])`:
Figure with `Scenario.records(colormap="tab10")`:
FIgure with `Scenario.records(color_dict={"Infected": "blue", "Fatal": "red", "Recovered": "green"})`:
We need create a new class for plotting because …
> Issue422 rebase

- covsirphy/__init__.py
- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/term.py
- covsirphy/cleaning/vaccine_data.py
- docs/markdown/INSTALLATION.md
- example/dataset_load.py
- example/usage_dataset.ipynb
- tests/conftest.py
- tests/test_datahub.py
- tests/test_dataloader.py
#429 
- `VaccineData` class and `DataLoader.vaccine()` will be added for data cleaning of vaccine data (the number of vaccinations).
- `VaccineData.subset()` will be added for subsetting.
- `VaccineData.total()`  will be added to calculate total values of vaccination.
- Document will be in https://lisphilar.github.io/covid19-sir/usage_dataset.html
> Issue429 vaccine

- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/vaccine_data.py
- tests/test_dataloader.py
#429 
- `DataLoader.pcr()` will correctly download the dataset of "Our World In Data" if the last download date was 12 hours ago at least.
- `VaccineData.records()` will be added as an alias of `VaccineData.subset()`.
- (Need discussion) Solution of filling NA in subset will be updated.
> update: update control of PCRData

- covsirphy/cleaning/pcr_data.py
This is related to #429.
Added more conditions for _pcr_check_preconditions().
> fix: improved _pcr_check_preconditions()

- covsirphy/__version__.py
Updated to version 2.13.3-epsilon-fu3 after merging pull 455.
> version 2.13.3-epsilon-fu3

- covsirphy/analysis/data_handler.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/util/error.py
This is related to issues #429.
Reworked province case in PCRData error handler and fixed `fillna()` issue in `T_DIFF` case.
> fix: province case, fillna() for T_DIFF case, added _records_diff_fill_ending()

- covsirphy/cleaning/pcr_data.py
- tests/test_datahub.py
#429
- Calculate cumulative number of tests using daily data, if necessary. (PCR data with "Our World In Data")
- FIx a bug in PCR data cleaning (the number of tests were replaced with NA values in `use_ourworldindata` method).
- Add a test with Sweden data.
> Issue429 pcr cumsum

- covsirphy/cleaning/linelist.py
- tests/test_dataloader.py
#449 
`LinelistData`:
- Remove `._raw`
- filename will be saved to `self._filename` and property `.raw` will return `.load(filename)`
- Not save the columns we will not use in data cleaning
> Issue449 raw3

- covsirphy/cleaning/jhu_complement.py
#450
Revert #464 (not including refactoring).
> revert: #464

- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/oxcgrt.py
- example/scenario_analysis_bra.py
- example/scenario_analysis_deu.py
- example/scenario_analysis_esp.py
- example/scenario_analysis_fra.py
- example/scenario_analysis_gbr.py
- example/scenario_analysis_grc.py
- example/scenario_analysis_jpn.py
- example/scenario_analysis_nld.py
- example/scenario_analysis_usa.py
- example/usage_quick.ipynb
- tests/test_param_tracker.py
- tests/test_scenario.py
#280 
Predict the parameter values of the near phases using OxCGRT scores. New phases will be added.
```Python
snl = cs.Scenario(jhu_data, population_data, "Japan")
snl.trend()
snl.estimate(cs.SIRF)
snl.fit_predict(oxcgrt_data)
snl.summary()
snl.simulate()
snl.history("Rt")
```
> Issue280 prototype

- covsirphy/analysis/data_handler.py
- covsirphy/analysis/example_data.py
- covsirphy/analysis/model_validator.py
- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/covid19datahub.py
- covsirphy/cleaning/dataloader.py
- covsirphy/cleaning/japan_data.py
- covsirphy/cleaning/jhu_complement.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/population.py
- covsirphy/cleaning/term.py
- covsirphy/cleaning/vaccine_data.py
- covsirphy/phase/phase_estimator.py
- covsirphy/phase/phase_series.py
- covsirphy/phase/phase_unit.py
- covsirphy/phase/sr_change.py
- covsirphy/simulation/estimator.py
- covsirphy/simulation/simulator.py
- covsirphy/util/file.py
- covsirphy/util/optimize.py
- covsirphy/util/plotting.py
- covsirphy/worldwide/policy.py
- tests/test_datahub.py
Follow-up for #401 and #405
- Refactoring
- Docstring update
- Test codes update
> Issue401 405 fu

- covsirphy/cleaning/jhu_complement.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/util/error.py
- tests/test_datahub.py
#401 
Remove `Availability` column from the output of `JHUData.show_complement()`.
> update: raise Error when failed in subsetting

- covsirphy/cleaning/jhu_data.py
- tests/test_datahub.py
#484 
- use total value of provinces as the country level data in China.
> update: use total of province level in China

- covsirphy/__version__.py
#483 
Dear @Inglezos , please merge this pull request after merging #492 if no issue found.
> version 2.14.0-delta

- docs/markdown/INSTALLATION.md
#480
docs: Notification regarding installation in Google Colab.
> docs: installation in Google Colab

- covsirphy/analysis/scenario.py
> add: Scenario.history() support actual confirmed

- covsirphy/util/plotting.py
#520
Close #520 for pull request #521
> fix: ValueError in line plotting

- covsirphy/analysis/model_validator.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/linelist.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/pyramid.py
- poetry.lock
- pyproject.toml
#481 
Drop swifter package from dependencies.
> config: update dependencies to support Python 3.9

- covsirphy/util/plotting.py
- tests/test_scenario.py
Follow up #521 
Fix argument error raised by #522 and add a test to confirm this problem was solved.
> fix: argument name of line_plot

- covsirphy/cleaning/jhu_complement.py
- covsirphy/cleaning/jhu_data.py
This is related to #514 and #500.
Reworked full complement conditions by adding _validate_recovery_period() method in JHUDataComplementHandler class, in order to determine if the raw recovered data (for a specific country) is valid or not, in order to apply full complement. Invalid partial recovery periods (elapsed intervals in days) are considered if they are outside the range [7, 90] days and this behavior is exhibited by more than 50% of these elapsed intervals.
Now the countries with full complement are only 24:
['American Samoa', 'Belgium', 'Germany', 'Dominica', 'Fiji', 'France', 'United Kingdom', 'Grand Princess', 'Guam', 'Saint Kitts and Nevis', 'Laos', 'Marshall Islands', 'Northern Mariana Islands', 'MS Zaandam', 'Netherlands', 'Puerto Rico', 'Solomon Islands', 'Sweden', …
> fix: reworked full complement conditions + added _validate_recovery_period()

- poetry.lock
- pyproject.toml
- setup.py
#516
Remove unused dependencies of dask package.
> Issue516 typing

- example/usage_theoretical.ipynb
#534 
Moved usage_theoritical.ipynb with updated comments from "docs" to "example" directory.
> docs: move usage_theoritical.ipynb to example dir

- covsirphy/analysis/data_handler.py
- tests/test_scenario.py
#478
Added `DataHandler.show_complement()` to show the details of complement with `Scenario` class.
> add: DataHandler.show_complement()

- covsirphy/cleaning/pcr_data.py
This is related to issue #490.
Added `_pcr_partial_complement_ending()` method in `PCRData` class for complementing ending unupdated testing records, by interpolating the previous valid `diff()` values.
> fix: added _pcr_partial_complement_ending()

- docs/markdown/TERM.md
- example/usage_dataset.ipynb
- example/usage_quick.ipynb
This is related to #531 and #478.
Added "recovery period" term and described `.show_complement()` usage.
> [doc]: added recovery period term + show_complement() usage

- docs/markdown/TERM.md
- example/usage_dataset.ipynb
- example/usage_quick.ipynb
#531 
Revive broken usage_dataset.ipynb and refactor of example files.
> issue531 docs: revive broken files

- .github/CONTRIBUTING.md
- docs/markdown/INSTALLATION.md
#479
Close #479 with update installation guide of Poetry.
> docs: installation guide of poetry

- docs/markdown/INSTALLATION.md
#555 
Update documentation of dataset guide regarding methods of `CountryData`.
> docs: dataset guide

- covsirphy/phase/trend.py
> update: max interation in curve fitting

- tests/test_dataloader.py
#429 
Update test codes of vaccination data to accept the change in the raw dataset. The first record date was changed from 15Dec2020 to 19Dec2020.
> test: update date range to accept change of raw

- covsirphy/__init__.py
- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/phase/phase_series.py
- covsirphy/phase/sr_change.py
- covsirphy/phase/trend.py
- covsirphy/util/plotting.py
#570 (S-R trend analysis)
- `covsirphy.line_plot_multiple()` function will be created to controll limit of x-axis.
- `Scenario.trend()` accept controll arugument of plotting.
- `Scenario.trend(xlim=(1000, None))` will set 1000 as lower limit of x-axis.
- When all recovered values are sufficiently larger than 0, lower limit of x-axis will be increased.
> Issue570 trend

- covsirphy/simulation/estimator.py
#570 and #575
- Set `None` as lower limit of x-axis in the figure of `Scenario.estimate_accuracy()`.
> Issue570 estimate accuracy

- covsirphy/analysis/scenario.py
#513
Register calculated delay value to instance of `Scenario` class to use the same value in prediction. Additionally, delay value will be shown when `Scenario.fit(delay=None)` as in the cases of `Scenario.fit(delay=14)`.
> fix: specified delay value not used in .predict()

- covsirphy/analysis/param_tracker.py
> fix: incorrect stdout when parameter estimation

- covsirphy/simulation/estimator.py
#578 
Default value will be changed from `Scenario.estimate(cs.SIRF, pruner="median")` to `Scenario.estimate(cs.SIRF, pruner="threshold", upper=0.5)` for speed-up.
> update: default to threshold pruner

- covsirphy/cleaning/jhu_data.py
> fix: not included province-level data

- covsirphy/visualization/colored_map.py
#535
Fixed a bug with country name discrepancy  of JHU data nad Natural Earth database.
> fix: not shown countries in global map

- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/population.py
- covsirphy/util/term.py
- covsirphy/visualization/colored_map.py
- covsirphy/visualization/vbase.py
- tests/test_datahub.py
- tests/test_visualize.py
#595, #598 and #599
- Close #595 
- Close #598 
- Close #599 
- Refactor
> Issue593 refactor

- covsirphy/cleaning/covid19datahub.py
> fix: stdout when downloading

- covsirphy/__version__.py
#614
Update version number to 2.16.2-beta
> version 2.16.2-beta

- covsirphy/visualization/vbase.py
> add: use plt.close() after plt.clf()

- Makefile
- covsirphy/analysis/scenario.py
- tests/conftest.py
- tests/test_policy_measures.py
- tests/test_scenario.py
- tests/test_visualize.py
#613
- Refactoring
- Update tests for speed-up
> Issue613 test

- covsirphy/cleaning/cbase.py
> update: ignore DeprecationWarning in CleaningBase

- covsirphy/visualization/vbase.py
> update: close figure

- covsirphy/__version__.py
- covsirphy/analysis/scenario.py
- example/usage_quick.ipynb
#644 
Show both of intercept and coefficients with `Scenario.fit()["intercept"]` and `Scenario.fit()["coef"]`.
> Issue644 coef

- .github/workflows/full_test.yml
- docs/markdown/INSTALLATION.md
- poetry.lock
- pyproject.toml
#647
- Close #647 
- Drop Python 3.6 support
> Drop Python 3.6 support

- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/visualization/colored_map.py
> fix: name discrepancies

- covsirphy/cleaning/oxcgrt.py
- covsirphy/visualization/colored_map.py
Folow-up for #671 
Fix `SettingWithCopyWarning` in `OxCGRTData` and `DeprecationWarning` in `ColoredMap`.
> fix: SettingWithCopyWarning

- covsirphy/trend/sr_change.py
- covsirphy/trend/trend_detector.py
- covsirphy/util/term.py
#670
Show MSE scores and phase duration in `TrendDetector.summary()`.
> Issue670 score

- tests/test_data_handler.py
- tests/test_trend.py
Follow-up of #679 and #681
In a test sccript, the first date of records in France was updated.
> test: update the first date of records in France

- covsirphy/util/filer.py
Foloow-up of #659 
If the top directory does not exist, the direcrtory will be created.
> update: make directory if not exist

- covsirphy/analysis/scenario.py
- example/usage_quick.ipynb
> add: removed_cols argument to .fit()

- covsirphy/__version__.py
- covsirphy/regression/reg_handler.py
#668
Fix: the number of cases was included in y with #704.
> Issue668 regressor fu

- covsirphy/__init__.py
- covsirphy/ode/ode_handler.py
- covsirphy/ode/ode_solver.py
- covsirphy/ode/sewirf.py
- covsirphy/util/term.py
- tests/test_ode.py
#698, #714, #721
To fix the last date of simulation results and to simplify the call tree of simulation, I created `ode.ode_solver._ODESolver` (internal only) and `ode.ode_datahandler.ODEHandler` (public) class.
They are not used in `Scenario` class at this time. Call tree of `Scenario.simulate()` will be changed later and `ODESimulator` will be deprecated.
Please check the usage of these classes with tests/test_ode.py::TestODEHandler.
Close #721
> Issue714 solver

- covsirphy/ode/mbase.py
- covsirphy/ode/ode_handler.py
- covsirphy/ode/ode_solver.py
- covsirphy/ode/ode_solver_multi.py
- covsirphy/ode/param_estimator.py
- covsirphy/ode/sewirf.py
- covsirphy/ode/sir.py
- covsirphy/ode/sird.py
- covsirphy/ode/sirf.py
- covsirphy/util/term.py
- tests/test_ode.py
#718
Added experimental methods to `ODEHandler` class. `.estimate()` calls the following methods internally.
- `ODEHandler.estimate_tau()`: Select tau value [min] which minimize the score of the metric. ODE parameter for each tau value will be guessed by .guess() classmethod of the model (cs.SIR, cs.SIRD, cs.SIRF).
- `ODEHnadler.estimate_params()`:  Estimate ODE parameter values of the all phases to minimize the score of the metric, using `optuna`.
> Issue718 separate estimator

- covsirphy/__init__.py
- covsirphy/visualization/compare_plot.py
- tests/test_visualize.py
#718 and #737
To prepare new approach of parameter estimation #718, `cs.ComparePlot()` and `cs.compare_plot()` will be created.
```Python
cs.__version__
data_loader = cs.DataLoader()
jhu_data = data_loader.jhu()
population_data = data_loader.population()
country = "Italy"
records_df = jhu_data.records(country, population=population_data.value(country))[0]
trend_detector = cs.TrendDetector(records_df)
start_dates, end_dates = trend_detector.sr().dates()
first_date = records_df.Date.min()
handler = cs.ODEHandler(cs.SIRF, first_date)
for (start_date, end_date) in zip(start_dates, end_dates):
y0_dict = records_df.set_index("Date").loc[start_date].to_dict()
handler.add(end_date, y0_dict=y0_dict)
tau, info_dict = handler.estimate(records_df)
df = …
```
> Issue718 accuracy plot

- covsirphy/analysis/model_validator.py
- covsirphy/analysis/param_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/vaccine_data.py
- covsirphy/ode/ode_handler.py
- covsirphy/phase/phase_series.py
- covsirphy/phase/phase_unit.py
- covsirphy/simulation/simulator.py
- covsirphy/util/term.py
- tests/test_model_validator.py
- tests/test_ode.py
#718 
- `ModelValidator` will be free from `MPEstimator`. (but, continue to depends on `Scenario`)
- `Term.date_obj()` will be deprecated and replaced with `Term.ensure_date()`
> Issue718 model validator

- covsirphy/analysis/scenario.py
- example/scenario_analysis.py
#737
Follow-up #743.
Fix a bug: `Scenario.estimate_accuracy()` shows records figure, not the expected figure.
> Issue737, follow-up

- covsirphy/analysis/example_data.py
- covsirphy/ode/mbase.py
- covsirphy/ode/sewirf.py
- covsirphy/ode/sir.py
- covsirphy/ode/sird.py
- covsirphy/ode/sirf.py
- tests/test_example_data.py
#718
The output of `ExampleData.specialized()` did not include "Date" column after #718 updates. This pull request fixes this problem. Tests will be also updated.
> Issue718 example data columns

- covsirphy/analysis/scenario.py
- docs/markdown/TERM.md
- example/usage_quick.ipynb
#731 
- Update default value from `Scenario.fit(delay=None)` to `Scenario.fit(delay=(5, 31)`.
- Update documentation of `Scenario.fit()` usage. https://lisphilar.github.io/covid19-sir/usage_quick.html#Short-term-prediction-of-parameter-values
- Add term definition of "delay period". https://lisphilar.github.io/covid19-sir/markdown/TERM.html
> Issue731 default value

- covsirphy/cleaning/covid19datahub.py
- covsirphy/cleaning/jhu_data.py
- tests/test_example_data.py
#760 
- Fix KeyError in `ExanpleData.cleaned()` caused by #761 updating.
- If `data_loader = cs.DataLoader(); data_loader.jhu()` has been called, `data_loader.population()` will not call `pandas.read_csv()`.
> Issue760 fu

- covsirphy/visualization/colored_map.py
#747
Rework for #746, legend label in colored label will be back.
Close #747.
> revise: add legend label in colored map

- covsirphy/analysis/phase_tracker.py
- tests/test_scenario.py
Follow-up #775
- Close #775 by fixing `ValueError` in `Scenario.simulate()` after `Scenario.retrospective()`.
> Issue775 simulate

- covsirphy/cleaning/jhu_data.py
> fix: not registered Infected in ._cleaned_df

- covsirphy/regression/regbase.py
> remove: data augmentation

- covsirphy/cleaning/country_data.py
- covsirphy/cleaning/jhu_data.py
#791
- Convert time to date automatically in `CountryData` and `JHUData`.
> update: convert time to date automatically

- covsirphy/analysis/scenario.py
- covsirphy/regression/reg_handler.py
#792 
An internal change:
Grid search of delay period will be done with `RegressionHandler` internally. This change is required for #792 because time series forecasting will not use delay period.
> update: grid search of delay done in handler

- covsirphy/analysis/scenario.py
- covsirphy/regression/param_decision_tree.py
- covsirphy/regression/param_elastic_net.py
- covsirphy/regression/rate_decision_tree.py
- covsirphy/regression/rate_elastic_net.py
- covsirphy/regression/reg_handler.py
- covsirphy/regression/regbase.py
> update: stop shffle in data splitting

- covsirphy/regression/param_decision_tree.py
- covsirphy/regression/param_elastic_net.py
- covsirphy/regression/param_svr.py
#802 and #806
- #802: For CV, k-fold will be replaced with `TimeSeriesSplit`.
- Close #806: select n_components from percentages
> Issue802 and Issue806

- covsirphy/regression/param_svr.py
- covsirphy/regression/reg_handler.py
#795 and #803
Correct a mistake in the description of SVR.
> fix: error in description

- docs/markdown/INSTALLATION.md
#800
Document how to install `covsirphy` with Anaconda.
> docs: installation guide with Anaconda

- covsirphy/regression/param_decision_tree.py
- covsirphy/regression/param_elastic_net.py
- covsirphy/regression/param_svr.py
- covsirphy/regression/rate_decision_tree.py
- covsirphy/regression/rate_elastic_net.py
- covsirphy/regression/rate_svr.py
- covsirphy/regression/reg_handler.py
- covsirphy/regression/regbase.py
- tests/test_scenario.py
> update: use all candiates of delay to create X

- covsirphy/__init__.py
- covsirphy/__version__.py
- covsirphy/visualization/line_plot.py
- covsirphy/visualization/scatter_plot.py
- covsirphy/visualization/vbase.py
- tests/test_visualize.py
> new: scatter plot

- covsirphy/regression/param_decision_tree.py
- covsirphy/regression/param_elastic_net.py
- covsirphy/regression/param_svr.py
- covsirphy/regression/regbase.py
#813
Refactor and update keys (best hyperparameters of regressors) of the output dictionary of `Scenario.fit()`.
> refactor: use best_params_

- covsirphy/regression/param_lightgbm.py
- covsirphy/regression/reg_handler.py
- poetry.lock
- pyproject.toml
#813
Add light gradient boosting machine regressor for forecasting with `lightgbm` package.
https://github.com/microsoft/LightGBM/tree/master/python-package
> Issue813 lightgbm

- covsirphy/__version__.py
- covsirphy/analysis/scenario.py
- covsirphy/regression/reg_handler.py
- covsirphy/regression/reg_pred_actual_plot.py
- covsirphy/regression/regbase.py
#815
- Show legend at the bottom of the figure
- Show sample sizes and scores of train and test data with legend
> Issue815 legend

- example/estimate_delay_days.ipynb
#829
Update estimate_delay_days.ipynb for the latest version 2.20.3.
> docs: update estimate_delay_days.ipynb

- covsirphy/ode/ode_handler.py
- covsirphy/ode/param_estimator.py
#833
User can select whether use constant liar or not with `Scenario.esitmate(<model>, constant_liar=False)` (default).
> update: user can contoll constant_liar

- example/scenario_analysis.py
> docs: use vaccine data in example script

- covsirphy/analysis/scenario.py
- covsirphy/regression/reg_handler.py
- covsirphy/regression/regbase.py
- example/usage_quick.ipynb
#813 and #815
- Use MAPE as evaluation metric for forecasting.
- Show MAPE score with percentage in the figure of `Scenario.fit()` via `Scenario.fit_accuracy()`.
> Issue813 mape

- covsirphy/analysis/scenario.py
- covsirphy/regression/feature_engineer.py
- covsirphy/regression/param_decision_tree.py
- covsirphy/regression/param_elastic_net.py
- covsirphy/regression/param_lightgbm.py
- covsirphy/regression/param_svr.py
- covsirphy/regression/reg_handler.py
- covsirphy/regression/regbase.py
#843
Refactoring for #843. Usage of user interface `Scenario.fit()` will not be changed and backward compatibility of `RegressionHandler` will be kept.
Applying delay period values and splitting data to train/test will be done by internal class `_FeatureEngineer` (before: `_RegressorBase._split()`). This is called by `Scenario.fit()` via `RegressionHandler.feature_engineering()`.
New enhancements regarding feature engineering will be also done by `_FeatureEngineer`.
> refactor: feature engineering by _FeatureEngineer

- README.md
> docs: README, funcitionalities

- covsirphy/__init__.py
- covsirphy/__version__.py
- covsirphy/loading/covid19datahub.py
- covsirphy/loading/dataloader.py
- covsirphy/loading/db_base.py
- covsirphy/loading/db_covid19dh.py
- tests/test_loading.py
#851 and #862
- Refactoring: add internal class `_RemoteDatabase` and `_COVID19dh` to download the dataset from COVID-19 Data Hub. `DataLoader` class will use it internally.
- Deprecate `COVID19DataHub` class because I think no users use it directory and `_COVID19dh` class plays its role.
> Issue851 refactor covid19dh handler

- covsirphy/__version__.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/country_data.py
- covsirphy/cleaning/japan_data.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/linelist.py
- covsirphy/cleaning/pyramid.py
- covsirphy/cleaning/vaccine_data.py
- covsirphy/loading/dataloader.py
#851
- Refactoring
- Deprecate `CleaningBase.load()`: this is not used by users directly.
> Issue851 refactor simplify

- covsirphy/__version__.py
- covsirphy/loading/db_cs_japan.py
- covsirphy/loading/db_owid.py
#851 and #891
- #851: follow-up for pull request #885
- Close #891
> fix: #891 and not cummurated vaccine data in Japan

- covsirphy/__version__.py
- covsirphy/loading/dataloader.py
- tests/test_loading.py
#851
Add `DataLoader.read_dataframe()`. This will be an alternative of `DataLoader.read_csv()`.
> Issue851 read dataframe

- covsirphy/__version__.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/population.py
- tests/test_cleaning/test_cbase.py
#862
Refactor: remove overlapped codes in __init__ of `CleaningBase` child classes.
> Issue862 refactor init

- covsirphy/__version__.py
- covsirphy/analysis/data_handler.py
- covsirphy/analysis/example_data.py
- covsirphy/cleaning/cbase.py
- covsirphy/cleaning/jhu_data.py
- covsirphy/cleaning/mobility_data.py
- covsirphy/cleaning/oxcgrt.py
- covsirphy/cleaning/pcr_data.py
- covsirphy/cleaning/population.py
- covsirphy/cleaning/pyramid.py
- covsirphy/cleaning/vaccine_data.py
- covsirphy/loading/dataloader.py
- covsirphy/loading/db_covid19dh.py
- covsirphy/loading/db_google.py
- tests/test_cleaning/test_jhu_data.py
- tests/test_cleaning/test_mobility.py
- tests/test_cleaning/test_oxcgrt.py
- tests/test_cleaning/test_pcr.py
- tests/test_cleaning/test_pyramid.py
- tests/test_cleaning/test_vaccine.py
- tests/test_example_data.py
#851, #899, #900, #901
- Close #899 
- Close #900 
- Close #901
- #851: users can set variables of OxCGRTData and MobilityData
> Issue 899, 900, 901, users can set variables of OxCGRTData and MobilityData

- covsirphy/analysis/phase_tracker.py
- covsirphy/analysis/scenario.py
- covsirphy/ode/ode_handler.py
#902 and #911
- Close #911: `Scenario(..., phases=["0th", "last"])` will work.
> fix: Scenario.estimate(..., phases=["last"]) not work

- covsirphy/analysis/scenario.py
- tests/test_cleaning/test_jhu_data.py
#954
Integers will be coverted to float to remove the error discussed in #954.
> Issue954 convert2float

- covsirphy/__version__.py
- covsirphy/analysis/phase_tracker.py
- covsirphy/ode/ode_solver_multi.py
- tests/test_phase_tracker.py
#957
- Raise `KeyError` in upper layer when initial values were not applied for some variables.
- Fix `KeyError` in SIR simulation.
> Issue957 with convertion

- covsirphy/loading/dataloader.py
- covsirphy/ode/mbase.py
#982 and #983
- Close #982 
- Trying #983
> Mbase explicitly to datetime

- covsirphy/loading/dataloader.py
> fix: TypeError with DataLoader.japan()

- covsirphy/cleaning/vaccine_data.py
- covsirphy/loading/dataloader.py
- tests/test_cleaning/test_vaccine.py
#991 and #969
Fix the error in subsetting of vaccination data in `DataLoader.vaccine()`.
```Python
cs.line_plot(vaccine_data.subset(country="Japan").set_index("Date"))
```
https://gist.github.com/lisphilar/bd342337784d1db37935296c756ad293
> Issue991 subset

- covsirphy/analysis/scenario.py
#1010
We will use only the past data (to today) as Y in prediction (#1010).
> update: only use the past data

- covsirphy/analysis/scenario.py
#1010
- fix: future phases of the template scenario is inherited
- fix: kwargs of Scenario.predict() is not applied to AutoMLHandler
> Issue1010 replace future phases

- covsirphy/analysis/scenario.py
#1010
Fix `ValueError: @end_date must be the same as/over 05Mar2022, but 02Mar2022 was applied.`
> fix: ValueError in adding phases

- covsirphy/__init__.py
- covsirphy/cleaning/cbase.py
- covsirphy/gis/gis.py
- covsirphy/gis/layer.py
- covsirphy/gis/subset.py
- covsirphy/util/error.py
- covsirphy/util/term.py
- tests/test_cleaning/test_jhu_data.py
- tests/test_gis/test_gis.py
- tests/test_gis/test_layer.py
- tests/test_gis/test_subset.py
- tests/test_trend.py
#1041 and #1059
- Created new class `GIS` to handle GIS data and locations
- `Geography` anf `DataCollector` was renamed to internal classes they were created after the latest stable release
- `NotRegistered` class was created to tell no records were registered to `GIS` class
- Close #1059 with updated `JHUData.area_name()'
> Issue1041 gis

- covsirphy/__init__.py
- covsirphy/downloading/db.py
- covsirphy/downloading/db_covid19dh.py
- covsirphy/downloading/db_cs_japan.py
- covsirphy/downloading/db_google.py
- covsirphy/downloading/db_owid.py
- covsirphy/downloading/downloader.py
- covsirphy/downloading/provider.py
- covsirphy/gis/gis.py
- covsirphy/gis/layer.py
- covsirphy/util/term.py
- tests/test_downloading.py
#1041 and #1045
Cleated `DataDownloader` class to retrieve recommended datasets of specified layer.
```Python
downloader = cs.DataDownloader(directory="input", update_interval=12, verbose=1)
downloader.layer()
downloader.layer(country="Japan")
downloader.layer(country="USA", province="Alabama")
downloader.citations(variables=["Confirmed", "Vaccinated_full"])
```
> Issue1045 data downloader

- covsirphy/downloading/db_google.py
- covsirphy/downloading/downloader.py
- covsirphy/downloading/provider.py
- covsirphy/gis/gis.py
- tests/test_downloading.py
#1045
- Fixed error handling in `DataDownloader`: raise `SubsetNotFoundError` when no data
- Save each level data regarding "Google Open Data" separately
> Issue1045 save google open data layers

- covsirphy/__init__.py
- covsirphy/__version__.py
- covsirphy/eda/eda.py
- covsirphy/engineering/engineer.py
- covsirphy/gis/gis.py
- covsirphy/regression/reg_handler.py
- covsirphy/util/error.py
#1045
- New class `EDA': tentative, methods and tests will be added later
- New bisic class of exception and tried to create a child class: exception should inherit a basic class for CovsirPhy. Not exceptions inherit exception classes of Python directory and codes are not well-organized.
> Issue1045 create eda

- covsirphy/analysis/scenario.py
#1045
Fix error in the old Python versions with walrus operator and #1078.
> fix: eror with walrus operator with old Python versions

- covsirphy/__init__.py
- covsirphy/science/causality.py
- covsirphy/science/ode_scenario.py
- covsirphy/util/error.py
#1045
- new: `ExperimentalWarming` and decorator of experimental method/function to explain that the method/fuction name, features and arguments may be changed later
- update: mark `Causality()` class as experimental
- update: mark `ODEScenario().predict()` method as experimental
- fix: ODEScenario().simulate() after.append() does not show new phases
- fix: ODE model name in ODEScenario.summary() is not a string
- fix; constant values are shown at the left side of ODEScenario.summary()
> Issue1045 fu ode scenario

- covsirphy/science/ode_scenario.py
#1045
- fix: `TypeError` of `ODEScenario().append(end=<int>)`
> fix: TypeError of ODEScenario().append(end=<int>)

- covsirphy/downloading/db_cs_japan.py
> fix: #1137

- docs/conf.py
#1150
Fix typo in docs/conf.py
> docs: fix typo regarding favicon

- covsirphy/science/_autots.py
- covsirphy/science/ml.py
- covsirphy/science/ode_scenario.py
#1136 and #477
- #1136: include the fitted model in the output of `MLEngineer().pca()`
- #477: user can specify the seed via `MLEngineer(seed)` and `ODEScenario().predict(seed)`
> Issue1136 fitted model

- covsirphy/science/ode_scenario.py
> fix: close #1166

- poetry.lock
- pyproject.toml
https://github.com/lisphilar/covid19-sir/issues/1174
Upgraded deptry to 0.2.5 and modified configuration accordingly.
> Upgraded deptry to 0.2.5

- poetry.lock
- pyproject.toml
#1174 
Use deptry 0.2.6 as proposed in #1174.
> config: use deptry 0.2.6

- poetry.lock
- pyproject.toml
> bumped deptry to 0.2.9

- covsirphy/downloading/_db.py
- covsirphy/downloading/_db_google.py
- covsirphy/downloading/_provider.py
#1223
- Close #1223: Skip updating files for "google" if file exist locally.
> update: skip updates if files, #1223

- covsirphy/downloading/_db_cs_japan.py
- covsirphy/dynamics/_trend.py
- covsirphy/dynamics/dynamics.py
- covsirphy/engineering/_cleaner.py
- covsirphy/gis/_layer.py
- covsirphy/gis/_subset.py
- example/03_ode.ipynb
- example/04_phase_dependent.ipynb
- pyproject.toml
- #1227
- config: raise error when warning
- fix Warnings in tests
- suppress internal warnings of dependencies (`pandas.DataFrame.update()`, classes of `ruptures`)
> config: raise error when warning

- poetry.lock
- pyproject.toml
> dev: close #1249

- covsirphy/downloading/_db.py
- covsirphy/downloading/_db_google.py
- covsirphy/downloading/_provider.py
- covsirphy/downloading/downloader.py
- covsirphy/dynamics/dynamics.py
- covsirphy/engineering/engineer.py
- covsirphy/gis/_geometry.py
- covsirphy/gis/_layer.py
- covsirphy/gis/gis.py
- covsirphy/science/_autots.py
- covsirphy/science/ml.py
- covsirphy/util/config.py
#1242
We will use `logger.info()` instead of `print()`.
> use logger.info() instead of print()

- covsirphy/util/config.py
- covsirphy/util/error.py
- tests/test_engineering/test_engineer.py
#1242
- Catch warnings with logger.
- Catch covsirphy-specific exceptions with logger.
> Catch warnings with logger

- covsirphy/science/ode_scenario.py
- example/05_scenario_analysis.ipynb
- tests/test_science/test_ode_scenario.py
#1239
Close #1239 by updating documentation and removing `ODEScenario.__eq__` and `ODEScenario.__ne__` because they are unstable.
> Follow-up Issue #1239

- poetry.lock
- pyproject.toml
#1271
Stop tests with multiple CPUs to avoid un-necessary FAILED.
> Stop tests with multiple CPUs to avoid un-necessary FAILED

- pyproject.toml
#1260
Close #1260 by fixing "coverage report not created".
> fix: coverage report not created

- .github/workflows/rebase-pull-requests.yml
#1199
Add automated rebase workflow.
> add automated rebase workflow

- covsirphy/dynamics/dynamics.py
- covsirphy/engineering/engineer.py
#1258
- use type hint in `DatEngineer`
- not accept None as `Dynamics(data_range)`
> use type hint in DatEngineer

- LICENSE
- oryx-build-commands.txt
update the last year in citation, 2020-2022 to 2020-2023
[LICENSE](https://github.com/lisphilar/covid19-sir/blob/main/LICENSE) is changed line no 189
> [Docs] update the last year in citation, 2020-2022 to 2020-2023

- example/01_data_preparation.ipynb
#1358
Close #1358 by updating Monkey Pox data URL as described on the issue page.
> close #1358 by updating Monkey Pox data URL

- README.md
#1356
Update "Citation" section of README to update the yeaer description from 2020-2022 to 2020-2023.
> update citation section of README

- covsirphy/engineering/engineer.py
- example/02_data_engineering.ipynb
#1415
- add DataEngineer().subset(get_dummies=True) as default
- update documentation to explain this change
> add DataEngineer().subset(get_dummies=True) as default

- example/01_data_preparation.ipynb
#1419
Fix "ValueError: cannot insert City, already exists" when running notebook 01_data_preparation.ipynb file.
> fix "ValueError: cannot insert City, already exists" when running notebook 01_data_preparation.ipynb

- covsirphy/downloading/_db_cs_japan.py
#1382
Update `DataDownloader` to include 4th and 5th vaccination data for Japan.
> update DataDownloader to include 4th and 5th vaccination data for Japan

- README.md
#1504
Close #1504 by updating the URL of pepy.tech badge.
> docs; close #1504

- README.md
- covsirphy/__citation__.py
- covsirphy/downloading/_db_cs_japan.py
- docs/conf.py
- close #1598
Update the last year in citation, 2020-2023 to 2020-2024.
> update the last year in citation, 2020-2023 to 2020-2024
